export const SPLASH_SCREEN_SCENE = 'SPLASH_SCREEN_SCENE';

export const SELECT_LANGUAGE_SCREEN_SCENE = 'SELECT_LANGUAGE_SCREEN_SCENE';

export const DISCLAIMER_SCREEN_SCENE = 'DISCLAIMER_SCREEN_SCENE';

export const SIGNIN_SCREEN_SCENE = 'SIGNIN_SCREEN_SCENE';

export const FORGOT_PASSWORD_SCREEN_SCENE = 'FORGOT_PASSWORD_SCREEN_SCENE';

export const SEND_FORGOT_SUCCESS_SCREEN_SCENE =
  'SEND_FORGOT_SUCCESS_SCREEN_SCENE';

export const SEND_OTP_SCREEN_SCENE = 'SEND_OTP_SCREEN_SCENE';

export const ENTER_OTP_SCREEN_SCENE = 'ENTER_OTP_SCREEN_SCENE';

export const SET_PIN_SCREEN_SCENE = 'SET_PIN_SCREEN_SCENE';

export const CONFIRM_PIN_SCREEN_SCENE = 'CONFIRM_PIN_SCREEN_SCENE';

export const SET_TOUCH_ID_SCREEN_SCENE = 'SET_TOUCH_ID_SCREEN_SCENE';

export const ENTER_PIN_SCREEN_SCENE = 'ENTER_PIN_SCREEN_SCENE';
